import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getPokemons } from "../api/pokemonApi";
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "react-query";
import RenderPokemon from "../components/RenderPokemon";
import Container from "../components/Container";

type PokemonType = {
  name: string;
  url: string;
};

export default function Home() {
  const pokemonQuery = useQuery("pokemon", getPokemons);

  if (pokemonQuery.isLoading) return <h1>Loading...</h1>;

  if (pokemonQuery.isError) return <h1>Error</h1>;

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <RenderPokemon pokemon={pokemonQuery.data.results} />
        </Container>
      </main>
    </>
  );
}
